// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW69NhRD3ieP492ak3r4A0XgVfVz0jvRI',
    appId: '1:233253700959:web:4158f926967fa4fa63e2ea',
    messagingSenderId: '233253700959',
    projectId: 'pisal-shoeapp-2026',
    authDomain: 'pisal-shoeapp-2026.firebaseapp.com',
    storageBucket: 'pisal-shoeapp-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLd1j_EcYi81p0pCmJaW5kbTwoCONf6o0',
    appId: '1:233253700959:android:de621f065518c37263e2ea',
    messagingSenderId: '233253700959',
    projectId: 'pisal-shoeapp-2026',
    storageBucket: 'pisal-shoeapp-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7a9NlhC7eWTO4qyG1KTOXvkkNHNgbOWQ',
    appId: '1:233253700959:ios:f357e00e9476f25963e2ea',
    messagingSenderId: '233253700959',
    projectId: 'pisal-shoeapp-2026',
    storageBucket: 'pisal-shoeapp-2026.firebasestorage.app',
    iosBundleId: 'com.example.shoeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7a9NlhC7eWTO4qyG1KTOXvkkNHNgbOWQ',
    appId: '1:233253700959:ios:f357e00e9476f25963e2ea',
    messagingSenderId: '233253700959',
    projectId: 'pisal-shoeapp-2026',
    storageBucket: 'pisal-shoeapp-2026.firebasestorage.app',
    iosBundleId: 'com.example.shoeShop',
  );

}